#!/bin/bash

pwd=$(find ~/.password-store/ -type f -name "*gpg" | \
	sed 's/.*.password-store\/\(.*\)\.gpg/\1/' | \
	rofi -mesg "alt+1: edit | alt+2: show" -dmenu)
# alt+1
if [ "$rofi_code" = "10" ]; then
	$TERMINAL -- pass edit $pwd && read
	exit $rofi_code
fi

if [ "$rofi_code" = "11" ]; then
	$TERMINAL bash -c "pass $pwd && echo -e '\n\n--end of pass output--\nPress enter to exit' && read"
	rofi -e $(pass $pwd)
	exit $rofi_code
fi

pass -c $pwd

if [ "$?" = "0" ]; then
	notify-send -u low "pass" "$pwd copied to clipboard"
fi
