#!/bin/bash

list_pass_cmd="find ~/.password-store/ -type f -name '*gpg' | \
	sed 's/.*.password-store\/\(.*\)\.gpg/\1/'"

cmd="$list_pass_cmd | fzf --color=$FZF_THEME"

echo $cmd
pwd=$(eval $cmd)
if [ -z $pwd ] || [ "$pwd" = "" ]; then
	echo "No password selected"
	exit 1
fi

# default option is copy instead of show
option="-c"
if [ "$1" = "" ]; then
	option="-c"
else
	option=$1
fi

pass $option $pwd
