#!/bin/bash
ssh_file="$HOME/Work/src/ssh_connections"

if [ "$1" != "" ]; then
	case $1 in
		e|-e)
			$EDITOR ${ssh_file}
			;;
		s|-s)
			cat ${ssh_file}
			;;
		*)
			echo "-e (edit)"
			exit 1
			;;
	esac
	exit 0
fi

line=$(cat ${ssh_file} | rofi -p ssh -dmenu)
rofi_status=$?

if [ "$line" = "" ]; then
	exit 1
fi

case $rofi_status in
	"10")
		echo $line
		;;
esac

ssh_conn=$(echo $line | cut -d\  -f1)
$TERMINAL ssh $ssh_conn
